# Generated by Django 2.2.1 on 2019-08-01 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        ('accounts', '0002_customuser_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('groupName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game', models.BooleanField(default=False)),
                ('action', models.CharField(default=None, max_length=15, null=True)),
                ('pot', models.PositiveSmallIntegerField(default=0)),
                ('noOfPlayers', models.PositiveSmallIntegerField(default=0)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='tables.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('user', models.OneToOneField(max_length=24, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('moneyInTable', models.PositiveSmallIntegerField()),
                ('turn', models.BooleanField(default=False)),
                ('poker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.Room')),
            ],
        ),
    ]
