# Generated by Django 2.2.6 on 2020-01-24 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20191212_1947'),
        ('tables', '0003_auto_20190804_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room', serialize=False, to='tables.Table')),
                ('action', models.CharField(default=None, max_length=15, null=True)),
                ('pot', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('user', models.OneToOneField(max_length=24, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('moneyInTable', models.PositiveSmallIntegerField()),
                ('turn', models.BooleanField(default=False)),
                ('poker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poker.Room')),
            ],
        ),
    ]
