# Generated by Django 3.0.2 on 2020-01-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='poker',
            new_name='room',
        ),
    ]
