# Generated by Django 2.2.1 on 2019-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_lastused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='lastUsed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
